package internal

// Update internal/cli/prompt.go, cmd/Profile-Converter/main.go, & README.md
const (
	FormatAYCD Format = iota
	FormatStellar
	FormatShikari
	FormatTrickle
)

// Represents a mapping of state shorthand names to their long names
var StateNames = map[string]string{
	"AL": "Alabama",
	"AK": "Alaska",
	"AZ": "Arizona",
	"AR": "Arkansas",
	"CA": "California",
	"CO": "Colorado",
	"CT": "Connecticut",
	"DE": "Delaware",
	"FL": "Florida",
	"GA": "Georgia",
	"HI": "Hawaii",
	"ID": "Idaho",
	"IL": "Illinois",
	"IN": "Indiana",
	"IA": "Iowa",
	"KS": "Kansas",
	"KY": "Kentucky",
	"LA": "Louisiana",
	"ME": "Maine",
	"MD": "Maryland",
	"MA": "Massachusetts",
	"MI": "Michigan",
	"MN": "Minnesota",
	"MS": "Mississippi",
	"MO": "Missouri",
	"MT": "Montana",
	"NE": "Nebraska",
	"NV": "Nevada",
	"NH": "New Hampshire",
	"NJ": "New Jersey",
	"NM": "New Mexico",
	"NY": "New York",
	"NC": "North Carolina",
	"ND": "North Dakota",
	"OH": "Ohio",
	"OK": "Oklahoma",
	"OR": "Oregon",
	"PA": "Pennsylvania",
	"RI": "Rhode Island",
	"SC": "South Carolina",
	"SD": "South Dakota",
	"TN": "Tennessee",
	"TX": "Texas",
	"UT": "Utah",
	"VT": "Vermont",
	"VA": "Virginia",
	"WA": "Washington",
	"WV": "West Virginia",
	"WI": "Wisconsin",
	"WY": "Wyoming",
}

// Represents a mapping of country shorthand names to their long names
var CountryNames = map[string]string{
	"AFG": "Afghanistan",
	"ALB": "Albania",
	"DZA": "Algeria",
	"ASM": "American Samoa",
	"AND": "Andorra",
	"AGO": "Angola",
	"AIA": "Anguilla",
	"ATA": "Antarctica",
	"ATG": "Antigua and Barbuda",
	"ARG": "Argentina",
	"ARM": "Armenia",
	"AWS": "Aruba",
	"AUS": "Australia",
	"AUT": "Austria",
	"AZE": "Azerbaijan",
	"BHS": "Bahamas",
	"BAH": "Bahrain",
	"BGD": "Bangladesh",
	"BRB": "Barbados",
	"BLR": "Belarus",
	"BEL": "Belgium",
	"BLZ": "Belize",
	"BEN": "Benin",
	"BMU": "Bermuda",
	"BTN": "Bhutan",
	"BOL": "Bolivia (Plurinational State of)",
	"BIH": "Bosnia and Herzegovina",
	"BWA": "Botswana",
	"BVT": "Bouvet Island",
	"BRA": "Brazil",
	"IOT": "British Indian Ocean Territory",
	"BRN": "Brunei Darussalam",
	"BGR": "Bulgaria",
	"BFA": "Burkina Faso",
	"BDI": "Burundi",
	"CPV": "Cabo Verde",
	"KHM": "Cambodia",
	"CMR": "Cameroon",
	"CAN": "Canada",
	"CYM": "Cayman Islands",
	"CAF": "Central African Republic",
	"TCD": "Chad",
	"CHL": "Chile",
	"CHN": "China",
	"CXR": "Christmas Island",
	"CCK": "Cocos (Keeling) Islands",
	"COL": "Colombia",
	"COM": "Comoros",
	"COG": "Congo",
	"COD": "Congo, Democratic Republic of the",
	"COK": "Cook Islands",
	"CRI": "Costa Rica",
	"HRV": "Croatia",
	"CUB": "Cuba",
	"CYP": "Cyprus",
	"CZE": "Czech Republic",
	"USA": "United States of America",
	"US":  "United States",
	"VNM": "Vietnam",
	"WSM": "Samoa",
	"YEM": "Yemen",
	"ZAF": "South Africa",
	"ZMB": "Zambia",
	"ZWE": "Zimbabwe",
}
